api_platform:
    title: Hello API Platform
    version: 1.0.0

    show_webby: false

    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true

    formats:
        json: ['application/json']
        jsonld: ['application/json+ld']
        html: ['text/html']
        multipart: ['multipart/form-data']