version: "3"

services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - /home/node_modules
      - ./front:/home/
 
  php:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      context: ./back
      dockerfile: ./Dockerfile
      target: php_dev
    volumes:
      - ./back/.docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ~/.config/composer:/home/prod/.composer
      - ./back:/srv/app

  database:
    image: postgres:15.4-alpine
    environment:
      POSTGRES_DB: esgi_challenge_s3
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"

  nginx:
    image: nginx
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./back:/srv/app
    ports:
      - "80:80"
    links:
      - php
    depends_on:
      - php

volumes:
  database_data:
