version: '3'

services:
  front-client:
    build: 
      context: .
      dockerfile: ./front-client/Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./monorepo:/home/monorepo
      - ./front-client:/home/front-client
      - /home/front-client/node_modules
      - /home/monorepo/node_modules
  server:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      context: ./back
      dockerfile: ./Dockerfile
      target: server
    volumes:
      - ./back:/srv/app
    links:
      - php
    ports:
      - '8888:80'
  php:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      context: ./back
      dockerfile: ./Dockerfile
      target: php_dev
    volumes:
      - ./back/.docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ~/.config/composer:/home/prod/.composer
      - ./back:/srv/app
  database:
    image: postgres:15.4-alpine
    environment:
      POSTGRES_DB: symfony
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"

  ###> symfony/mailer ###
  mailer:
    image: schickling/mailcatcher
    ports: ["1025:1025", "1080:1080"]
###< symfony/mailer ###

volumes:
  database_data:
