version: "3"

services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - /home/node_modules
      - ./front:/home/
  server:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      context: ./back
      dockerfile: ./Dockerfile
      target: server
    volumes:
      - ./back:/srv/app
    links:
      - php
    ports:
      - "8888:80"
  php:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      context: ./back
      dockerfile: ./Dockerfile
      target: php_dev
    volumes:
      - ./back/.docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ~/.config/composer:/home/prod/.composer
      - ./back:/srv/app
  database:
    image: postgres:15.4-alpine
    environment:
      POSTGRES_DB: esgi_challenge_s3
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"

  ###> symfony/mailer ###
  mailer:
    image: schickling/mailcatcher
    ports: ["1025:1025", "1080:1080"]
###< symfony/mailer ###

volumes:
  database_data:
