export const specialisationsDoctolib = [
  "Médecin généraliste",
  "Dentiste",
  "Gynécologue",
  "Cardiologue",
  "Pédiatre",
  "Dermatologue",
  "Ophtalmologiste",
  "Rhumatologue",
  "Gastro-entérologue",
  "Chirurgien orthopédique",
  "Neurologue",
  "Psychiatre",
  "Oto-rhino-laryngologiste (ORL)",
  "Urologue",
  "Radiologue",
  "Endocrinologue",
  "Néphrologue",
  "Orthodontiste",
  "Oncologue",
  "Allergologue"
]
