# name: 🧪 Test CI/CD

# on:
#   push:
#     paths:
#       - ".github/workflows/**"

# jobs:
#   test-github-actions-Back:
#     uses: ./.github/workflows/buildAndPushBack.yaml
#     secrets: inherit # <= this one
